/**
 * Cardano Stakeholder Authenticator Service
 * A service to verify stakeholder ownership and provide stake history for addresses
 *
 * OpenAPI spec version: 0.0.2
 * Contact: contact@pegasuspool.info
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.pegasus.csas.server.model

data class AuthLoginPost (
    val address: String,
    val password: String
)