/**
 * Cardano Stakeholder Authenticator Service
 * TBA
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@pegasuspool.info
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.pegasus.csas.server.model

/**
 *
 * @param address An address associated associated with the account the user is logging into.
 * @param password The user's new password.
 */
data class ForgotPasswordStatusPost(
    val address: String,
    val password: String?
)
