/**
* Cardano Stakeholder Authenticator Service
* TBA
*
* OpenAPI spec version: 1.0.0
* Contact: contact@pegasuspool.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.pegasus.csas.server.model

/**
 * 
 * @param epoch The epoch the amount and delegated_to values refer to
 * @param delegatedTo The poolID the stake was delegated to in the specified epoch
 * @param amount The amount that was delegated in the specified epoch (in lovelaces)
 */
data class StakeHistory (
    /* The epoch the amount and delegated_to values refer to */
    val epoch: kotlin.Int,
    /* The poolID the stake was delegated to in the specified epoch */
    val delegatedTo: kotlin.String,
    /* The amount that was delegated in the specified epoch (in lovelaces) */
    val amount: kotlin.Long
) {

}

