/**
 * Cardano Stakeholder Authenticator Service
 * TBA
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@pegasuspool.info
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.pegasus.csas.server.model

/**
 *
 * @param userId The userId from the service provider's system. This is used to distinguish address verification requests from different users.
 * @param password The password used to create the user upon successful address verification. This field is mandatory if the userId provided does not map to an existing user.
 */
data class VerificationStatusPost(
    val userId: String,
    val password: String?
)
